### ISSUE TITLE
s2i-enable postfix

### ISSUE THREAD

**Issue by TomasTomecek** [container-images/postfix#12]

**Comment by phracek** [comment]
Do we want to use both approaches in one GitHub repo? Like `postfix` container installed by `dnf install postfix` and the other one approach `s2i install`.

**Comment by TomasTomecek** [comment]
There is no `s2i install`. We likely want to have only s2i version: for example see how I s2i-enabled vsftpd to understand what it means: https://github.com/container-images/vsftpd/pull/3

**Comment by phracek** [comment]
s2i images make sense. Where will be module based containers?

**Comment by TomasTomecek** [comment]
I don't understand the question.

**Comment by phracek** [comment]
Well I will rephrase it a bit.

This issues is about s2i-enable postfix container images, which is fine. It means, this GitHub repo will contain Dockerfile with s2i-enable postfix container image, right?

Once Modularity team release a new set of modules for F27, and we would like to create a postfix container image based on postfix module. Where will be stored Dockerfile for module based postfix container image?
In the same GitHub as s2i-enable container image but with different suffix, like Dockerfile.module_based?
