### ISSUE TITLE
Verbose stdout

### ISSUE THREAD

**Issue by kutzi** [container-images/postfix#6]
When running the container it prints looots of lines like:

"postfix/postfix-script: the Postfix mail system is running: PID: 74"

I guess it's because of line 20 here:
https://github.com/container-images/postfix/blob/master/files/start_postfix.sh#L20

Is it really necessary to be so verbose?

**Comment by TomasTomecek** [comment]
Gotta say that I don't understand the loop, looks like a code for debugging; @phracek any idea?

**Comment by phracek** [comment]
Yeah, it was only for debugging propose inside OpenShift.
It can be removed.

**Comment by phracek** [comment]
Yeah, it was for debugging propose in OpenShift. 
echo cmd can be removed. But rest has to stay, Otherwise, there is no possibility how to check if postfix is running or not.

**Comment by TomasTomecek** [comment]
> Otherwise, there is no possibility how to check if postfix is running or not.

And why do we need to check such thing? Once the postfix process dies, the container "just" quits.
